services:
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
    container_name: frontend-dev

  backend-dev:
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    ports:
      - 6453:6453
    volumes:
      - ./backend:/usr/src/app
    container_name: backend-dev
